server:
  port: 8061


spring:
  freemarker:
    charset: utf-8
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    suffix: .ftl
    settings:
      datetime_format: yyyy-MM-dd HH:mm:ss
      default_encoding: UTF-8
      auto_import: common/common.ftl as common
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/houses?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pwd123
    hikari:
      auto-commit: true
      idle-timeout: 180000
      connection-timeout: 30000
      max-lifetime: 1800000
      minimum-idle: 5
      maximum-pool-size: 15
      pool-name: MYHikariCP
  mail:
    username: spring_boot@163.com
    host: smtp.163.com
    password: abc123455
    properties:
      mail:
        smtp :
          auth : true





mybatis-plus:
  type-aliases-package: com.example.common.model
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      field-strategy: not_null

file:
  prefix: http://127.0.0.1:8081/images

domainName: 127.0.0.1:8061